[alembic]
script_location = modern/alembic

[alembic:env]
# runtime database url will be read from env DATABASE_URL

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s

# sqlalchemy.url will be set at runtime from DATABASE_URL

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy

[logger_alembic]
level = WARN
handlers = console
qualname = alembic

